version: '2.2'

services:
  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs-demo-ts
    ports:
      - "9000:9000"
    volumes:
      - .:/home/node/app
    command: npm start